#{}创建的是空字典，而非空集合
print({},set(),type({}),type(set()),'\r\n')
#
print({'a','b','c','d',},set(range(9)),type(set(range(9))),'\r\n')
#
print(set(range(1,60,5)),'\r\n')
#
print({1,2,3,4,5,6,'a','b','b',10.36},'\r\n')
#利用set（）可以把字符串、列表或元组转换为集合
print(set('abcdef123456'),'\r\n')
#
print(set([1,2,3,3,5,6,'a','b','c','c','e','f']),'\r\n')
#
print(set((1,2,3,3,5,6,'a','b','c','c','e','f')),'\r\n')
#利用集合的套嵌可以创建伪二维集合
print({frozenset({1,2,3,4,5}),frozenset({2,3,4,5,6})},'\r\n')
#
print({(1,2,3,4,5),(2,3,4,5,6)},'\r\n')
#添加元素
s={1,2,3}
s.add('a')
print((s),'\r\n')
#修改集合
s={1,2,3}
s.update({3,6,9},{'a','b'},{True,False})
print((s),'\r\n')
#
s.intersection_update({1,3,6,9},{1,'a',3,'b'},{True,False,3})
print((s),'\r\n')
#
s.difference_update({3,6,9},{'a','b'},{False,3})
print((s),'\r\n')
#
s={1,2,3,4,5,6};t={4,5,6,'a','b','c'}
s.symmetric_difference_update(t)
print((s),'\r\n')
#删除元素
s=set(range(10))
print((s),'\r\n')
#
s.remove(4)
print((s),'\r\n')
#
s.discard(3)
print((s),'\r\n')
#
s.pop()
print((s),'\r\n')
#
s.clear()
print((s),'\r\n')
#
del s
#访问集合
for x in {1,2,3,4,5,6}:print((x),'\r\n')
#集合并集、交集、差集和对称差集
s={1,2,3,'a','b'};t={3,'a','b','c'}
print((s|t,s&t,s-t,s^t),'\r\n')
#
s|=t
print((s,t),'\r\n')
#
print({1,2,3,'a','b'}.union({3,'a','b','c'},{66}),'\r\n')
#
print({1,2,3,'a','b'}.intersection({3,'a','b','c'},{3,'a'}),'\r\n')
#
print({1,2,3,'a','b'}.difference({3,'a','b','c'},{2,3,'a'}),'\r\n')
#
print({1,2,3,'a','b'}.symmetric_difference({3,'a','b','c'}),'\r\n')
#长度、求和、最小和最大
s=set(range(10))
print((s),'\r\n')
#
print(len(s),sum(s),max(s),min(s),'\r\n')
#
x={1,2,3};y={'a','b','c'};z={1,2};w={'a','b'}
print((x>y,s<=y,z<x,y>=w),'\r\n')
#
print(z.issubset(x),y.issuperset(w),'\r\n')
#
print(x.isdisjoint(y),x.isdisjoint(z),'\r\n')
#
print((z in x,2 in x,w not in y,'a'not in y),'\r\n')
#复制集合
a={1,2,3}
b=a
c=a.copy()
import copy
d=copy.copy(a)
print((a,b,c,d),'\r\n')
#
print(id(a),id(b),id(c),id(d),'\r\n')
#未运行出结果
a.union({'a'},'\r\n')
#
print((a,b,c,d),'\r\n')
#
print(id(a),id(b),id(c),id(d),'\r\n')
#
a.add('a')
print((a,b,c,d),'\r\n')
#
print(id(a),id(b),id(c),id(d),'\r\n')
#
b.add('b')
print((a,b,c,d),'\r\n')
#
print(id(a),id(b),id(c),id(d),'\r\n')
#
c.add('c')
print((a,b,c,d),'\r\n')
#
print(id(a),id(b),id(c),id(d),'\r\n')
#
d.add('d')
print((a,b,c,d),'\r\n')
#
print(id(a),id(b),id(c),id(d),'\r\n')
